server:
  port: 8884

spring:
  application:
    name: springcloud-eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
  instance:
    hostname: localhost
